// Code generated by "stringer -type TransactionType"; DO NOT EDIT.

package test

import "strconv"

const _TransactionType_name = "SplitMerge"

var _TransactionType_index = [...]uint8{0, 5, 10}

func (i TransactionType) String() string {
	i -= 3
	if i < 0 || i >= TransactionType(len(_TransactionType_index)-1) {
		return "TransactionType(" + strconv.FormatInt(int64(i+3), 10) + ")"
	}
	return _TransactionType_name[_TransactionType_index[i]:_TransactionType_index[i+1]]
}
